import localFont from "next/font/local";
import { Sora } from "next/font/google";
import "./globals.css";
import { AppKit } from "../context/appkit";

const font = Sora({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AppKit> {children}</AppKit>
      </body>
    </html>
  );
}
